# Generated by Django 6.0.3 on 2026-03-19 17:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_cartitem_product'),
        ('products', '0002_product_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='spare_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.sparepart'),
        ),
    ]
